# Generated by Django 4.2.7 on 2023-11-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=60)),
                ('club', models.CharField(max_length=60)),
                ('price_euro', models.IntegerField()),
                ('games', models.IntegerField()),
                ('goals', models.IntegerField()),
            ],
        ),
    ]
