# Generated by Django 4.2.7 on 2023-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_players_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='club',
            new_name='count_of_club',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='football_player_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='games',
            new_name='matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='price_euro',
        ),
    ]
