# Generated by Django 4.2.7 on 2023-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_club_player_count_of_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='count_of_club',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='football_player_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
